### ISSUE TITLE
[Bug]: Fail on unknown fields

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/dofigen#175]
### What happened?

I made a dofigen config file with mistakes in fields names (add instead of adds).

The field was just ignored and I did not understand why my Dockerfile was not working.

It should be nice fail on unknown fields: https://serde.rs/container-attrs.html#deny_unknown_fields

And also to have some alias to avoid this kind of problems: https://serde.rs/field-attrs.html#alias

### Version

1.2.0

**Comment by shiipou** [comment]
@taorepoara Maybe it should not fail but show warning in the console. (COLORED one)

**Comment by taorepoara** [comment]
> @taorepoara Maybe it should not fail but show warning in the console. (COLORED one)

I think that might be an evolution for later, because the Yaml lib that we uses only fails or does not give us any info
