### ISSUE TITLE
[Bug]: when using -f, generate a `<dockerfile-name>.dockerignore`

### ISSUE THREAD

**Issue by shiipou** [lenra-io/dofigen#195]
### What happened?

With docker, when we build using `-f` arg, it lookup the `<dockerfile-name>.dockerignore` file, if it didn't find it, it will load `.dockerignore`.

We need to generate the `<dockerfile-name>.dockerignore` instead of a `<dockerfile-name>.dockerignore` if `-f` is provided to dofigen.

### Version

1.4.0

**Comment by taorepoara** [comment]
This would include breaking changes to the CLI API
