### ISSUE TITLE
[Task] CI: Don't release if not next version

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/dofigen#27]
## What should be done 
Do not run the release job if Semantic Release does not find next version.

## Technical recommandation
Check if the next version var exists at the beginning of the job and stop if not.

**Comment by taorepoara** [comment]
@shiipou You could have some recommandations for this

**Comment by shiipou** [comment]
You can use [this action](https;//github.com/shiipou/sem-release) instead of semantic release, or use [this plugin](https://github.com/felipecrs/semantic-release-export-data#github-actions-example) for semantic-release to output the version number.
