### ISSUE TITLE
[Bug]: Can't use reqwest from Dofigen Docker Image

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/dofigen#308]
### What happened?

Tried to use the Dofigen Docker image but got an error.

Here is an example to reproduce:

```bash
echo "fromImage: lenra/dofigen:beta" > dofigen.yml
docker run --rm -it -v $(pwd):/app lenra/dofigen:2.2.0-beta.1 gen
```

### Version

2.2.0-beta.1

### Relevant log output

```Shell
Add resource dofigen.yml a726876cb72cf7efad73a5eba2e2c70b3905c2103ad3cde8adc5bb6e17d3e51d
error: error sending request for url (https://registry.hub.docker.com/v2/namespaces/library/repositories/postgres/tags/17)
```

<sub><a href="https://huly.app/guest/lenra?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM3N2MxM2U3Y2M1YTc4NTQyZDJhNTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVibmVzcXdpLWxlbnJhLTY2YzQ1NjEwLWEwZmY2MDljODEtYzQyZjYxIn0.x9LuTygPXH4QEEqEd6iKLwWNxHEX7IFBGip4F2KJICQ">Huly&reg;: <b>DOFIG-305</b></a></sub>

**Comment by Drauna** [comment]
I face a similar issue when I tried to run last Dofigen Docker image :

```
docker run --rm -it -v ./scripts:/app lenra/dofigen
```

Log was :

```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "dofigen": executable file not found in $PATH: unknown.
```
Same issue in 2.0.0

**Comment by taorepoara** [comment]
@Drauna  I fixed a part of the Docker image problem, but not totally...

You can use the image tag `beta` to get my last modification on this.

I'll work on this issue tomorrow

**Comment by taorepoara** [comment]
@Drauna Just fixed it in the latest beta version. Can you try with the image `lenra/dofigen:2.2.0-beta.2` please ?

This one works fine now on my computer.

**Comment by Drauna** [comment]
Hi @taorepoara ,
I give a try to this new tag and now it runs without the error.
I've some more but I think it's my source yaml the issue.
Thank you for the really quick fix.
